export const FETCH_TASK_DATA = "FETCH_TASK_DATA"
export const SAVE_TASK_DATA = "SAVE_TASK_DATA"
export const FETCH_USERS = "FETCH_USERS"
export const FETCH_PLAN_DATA = "FETCH_PLAN_DATA"
export const SAVE_PLAN_DATA = "SAVE_PLAN_DATA"
export const FETCH_CUSTOMER_DATA = "FETCH_CUSTOMER_DATA"
export const SAVE_CUSTOMER_DATA = "SAVE_CUSTOMER_DATA"
export const SAVE_DATA = "SAVE_DATA"

export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";